



// $(document).ready(function(){
//     $('a').on('click',function(event){
//         event.preventDefault()

//             $('a').on('click',function(){
//                 $('body').addClass('menu-open');

//         }); 

//         //    const link = $(this).attr('href');
        
//         //    setTimeout(function(){
//         //             location.href = link;
//         //         },2000);      
//             });   
//         }); 
        


$(document).ready(function(){

    $('.bg').animate({'opacity': '0','z-index': '-1'},1800);
  
    $('.copy').animate({'opacity': '1'},5000);
   
});










 





